name: Scan

on: push

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: 42Crunch/api-conformance-scan-action@master
      with:
        api-token: ${{ secrets.API_TOKEN }}
        platform-url: https://platform.42crunch.com
        command: crunch42_scan json-report convert-to-sarif $report_path $sarif_path
        report-path: report.json
        
    - uses: actions/upload-artifact@v2
      with:
        name: sarif-report
        path: report.sarif
        
    - uses: github/codeql-action/upload-sarif@v2
      with:
        # Path to SARIF file relative to the root of the repository
        sarif_file: report.sarif
        # Optional category for the results
        # Used to differentiate multiple results for one commit
        category: my-analysis-tool

    - uses: 42Crunch/api-conformance-scan-action@master
      with:
        api-token: ${{ secrets.API_TOKEN }}
        platform-url: https://platform.42crunch.com
        report-path: report.json

